name: Build and Publish Python Package

on:
  push:
    branches:
      - WP-2-Set-up-Nexus-integration

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          pip install wheel twine

      - name: Build package
        run: python slackbot/setup.py sdist bdist_wheel

      - name: Verify built file
        run: ls -l dist/

      - name: Publish to Nexus
        run: |
          twine upload --repository-url http://52.16.240.11:8081/repository/slackbot-releases/ dist/*
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}