name: Build and Publish Python Package

on:
  push:
    branches:
      - WP-2-Set-up-Nexus-integration

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Nexus Repository Publisher for GitHub Actions
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          groupId: com.example
          artifactId: my-python-package
          version: 1.0.0
          repositoryUrl: http://52.16.240.11:8081
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
