name: Build and Publish Python Package

on:
  push:
    branches:
      - WP-2-Set-up-Nexus-integration

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Build package
        run: python scripts/setup.py sdist bdist_wheel
      - name: Verify built file
        run: ls -l dist/
      - name: Nexus Repository Publisher for GitHub Actions
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: http://52.16.240.11:8081
          username: admin
          password: nexusnexus
          format: pypi
          repository: slack-bot-releases
          coordinates: version=1.2.0 artifactId=slack-bot
          assets: extension=whl
          filename: dist/slack_bot-1.2.0-py3-none-any.whl