name: Build and Publish Python Package

on:
  push:
    branches:
      - WP-2-Set-up-Nexus-integration

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Nexus Repository Publisher for GitHub Actions
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: http://52.16.240.11:8081
          username: admin
          password: nexusnexus
          format: pypi
          repository: slack-bot-releases
          coordinates: version=1.2.0
          assets: extension=tar.gz
          filename: dist/*
